Feature/grpc
dragonflyoss/Dragonfly2 pull request #1007
Opened 2022-01-18 15:10 UTC by 244372610

## Description
refactor GRPC communication framework

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-20 03:43 UTC, gaius-qi requested changes

2022-01-20 03:43 UTC, gaius-qi commented on pkg/rpc/scheduler/server/server.go
> +	ReportPieceResult(context.Context, scheduler.Scheduler_ReportPieceResultServer) error
Designed according to the native `GRPC` function.

2022-01-21 02:43 UTC, gaius-qi requested changes

2022-01-21 02:43 UTC, gaius-qi commented on scheduler/rpcserver/rpcserver.go
> +	metrics.RegisterPeerTaskCount.Inc()
Mtrics is put back in the proxy and reply proxy code.

2022-01-26 07:20 UTC, zzy987 commented on pkg/rpc/balancer.go
> +	// As we want to do the connection management ourselves, we don't set up connection here.
Are the comments here out of date?

2022-01-26 15:25 UTC, 244372610 commented on pkg/rpc/balancer.go
> +	// As we want to do the connection management ourselves, we don't set up connection here.
Comments still apply

2022-03-04 03:57 UTC, gaius-qi requested changes

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/cdnsystem/testdata/seed_piece_info.json
> +  "aaaaaaaaaaaaaaa": [
Rename `foo` or `bar`.

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/cdnsystem/testdata/seed_piece_info.json
> +  "bbbbbbbbbbbbbbb": [
Rename `foo` or `bar`.

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/dfdaemon/testdata/pieces.json
> +  "aaaaaaaaaaaaaaa": {
Rename `foo` or `bar`.

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/dfdaemon/testdata/pieces.json
> +  "bbbbbbbbbbbbbbb": {
Rename `foo` or `bar`.

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/dfdaemon/testdata/pieces.json
> +    "piece_md5_sign": "aaaaaaaaaaaaaaa_sign",
Rename `foo` or `bar`.

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/dfdaemon/testdata/pieces.json
> +    "piece_md5_sign": "bbbbbbbbbbbbbb_sign",
Rename `foo` or `bar`.

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/scheduler/client/mocks/mock_client.go
>  // Code generated by MockGen. DO NOT EDIT.
Change file name to `client_mock.go`.

2022-03-04 03:57 UTC, gaius-qi commented on pkg/rpc/scheduler/mocks/mock_scheduler.go
> +// Code generated by MockGen. DO NOT EDIT.
Rename file name to `scheduler_mock.go`.

2022-03-04 03:57 UTC, gaius-qi commented on scheduler/resource/cdn_mock.go
>  	dfnet "d7y.io/dragonfly/v2/internal/dfnet"
Revert this file.

2022-05-16 06:13 UTC, closed without merging