Optimized the log creation
dragonflyoss/Dragonfly2 pull request #1058
Opened 2022-02-10 15:07 UTC by 244372610

## Description

Optimized the log creation

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-11 03:18 UTC, jim3ma requested changes

2022-02-11 03:18 UTC, jim3ma commented on internal/dflog/loginit.go
> +	}
这里也重置一下 `levels = nil`吧，init 里面有创建过，重置一下，释放掉多余的资源

2022-02-22 08:02 UTC, 244372610 commented on internal/dflog/loginit.go
> +	}
done

2022-03-04 08:54 UTC, hyy0322 approved these changes

2022-03-17 04:23 UTC, jim3ma approved these changes
LGTM

2022-03-17 10:14 UTC, qwtsc approved these changes
lgtm

2022-03-17 10:15 UTC, merged