feat: write log to file
dragonflyoss/Dragonfly2 pull request #1236
Opened 2022-04-08 14:33 UTC by anjia0532

Signed-off-by: AnJia <anjia0532@gmail.com>

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Code compiles correctly.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-04-10 12:36 UTC, 244372610 submitted a review, later dismissed

2022-04-11 02:57 UTC, gaius-qi requested changes

2022-04-11 02:57 UTC, gaius-qi commented on deploy/docker-compose/docker-compose.yaml
> +      test: ["CMD-SHELL", "/bin/grpc_health_probe -addr=0.0.0.0:65000 || exit 1"]
`/bin/grpc_health_probe -addr=0.0.0.0:65000` => `/bin/grpc_health_probe -addr=:65000`

2022-04-11 02:57 UTC, gaius-qi requested changes

2022-04-11 02:57 UTC, gaius-qi commented on deploy/docker-compose/template/cdn.template.yaml
> +verbose: false
`verbose: true`

2022-04-11 03:07 UTC, gaius-qi approved these changes
LGTM

2022-04-11 03:09 UTC, gaius-qi approved these changes
LGTM

2022-04-11 03:09 UTC, jim3ma approved these changes
LGTM

2022-04-11 03:31 UTC, merged