Feature: use a golang native file server to replace nginx
dragonflyoss/Dragonfly2 pull request #1258
Opened 2022-04-17 06:36 UTC by zzy987

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-04-17 07:16 UTC, anjia0532 commented
用golang写静态文件服务器 替换nginx我是认可的，只是有几点担心
1. 需要压测来评估 nginx 和 golang 静态文件的吞吐（QPS/TPS）和性能（比如内存），可以用 k6,gatling,wrk等工具来实现，如果集成到 e2e 更好，需要综合测试 kb,mb,gb 三种量级的文件对于 nginx/golang 的影响，假设（我对这块不熟悉），golang是整个读取 load 到内存，那么测kb/mb时没问题，但是到gb时可能会oom
2. 需要评估代码会不会逃逸/越权访问未授权目录， 比如 `http.FileServer(http.Dir("/path/to/static-dir"))` ,url访问的是 `http://example.com/../xxxx.tar.gz`  会不会访问到 `/path/to/` 目录
3. nginx 会根据后缀给resp返回 content-type , golang 如果不返回或者默认写死一个，会不会影响下游使用？
4. golang 静态文件服务器支不支持 断点续传、下载

2022-04-27 09:21 UTC, jim3ma requested changes

2022-04-27 09:21 UTC, jim3ma commented on cdn/fileserver/fileserver.go
> +		for mappedErr == syscall.EMFILE {
Add max retry count to avoid client cancelled.

2022-04-27 09:28 UTC, gaius-qi requested changes

2022-04-27 09:28 UTC, gaius-qi commented on cdn/cdn.go
> +		if err := s.fileServer.ListenAndServe(); err != nil {
HTTP server need shutdown.

2022-04-27 10:07 UTC, yxxhero commented on cdn/cdn.go
> +		if err := s.fileServer.ListenAndServe(); err != nil {
两种服务的启动 我记得有种更优雅的方式

2022-04-28 11:54 UTC, zzy987 commented on cdn/cdn.go
> +		if err := s.fileServer.ListenAndServe(); err != nil {
> 两种服务的启动 我记得有种更优雅的方式

请问更优雅的方式具体是什么呢？

2022-04-29 04:52 UTC, jim3ma commented on cdn/cdn.go
> +		if err := s.fileServer.ListenAndServe(); err != nil {
你这里的 error 需要判断一下，因为有主动 stop 的情况，不能所有错误都 fatal 的，因为 fatal 是属于 panic 的

2022-04-29 07:09 UTC, jim3ma approved these changes
LGTM

2022-04-29 07:12 UTC, merged