chore: make dfget and dfcache package name follow NVR convention
dragonflyoss/Dragonfly2 pull request #1321
Opened 2022-05-21 06:01 UTC by eryugey

NVR requires packages to be named as Name-Version-Release format, so
change dfget and dfcache package name to follow NVR convention.

So the name is dfget or dfcache, version is $SEMVER, e.g. "2.0.1",
the following are all release. e.g.

old: dfget_2.0.1-1_<commit>_linux_amd64.rpm
new: dfget-2.0.1-1.<commit>.linux_amd64.rpm

Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-05-25 07:52 UTC, jim3ma approved these changes
LGTM

2022-05-31 14:10 UTC, gaius-qi requested changes

2022-05-31 14:22 UTC, eryugey commented on Makefile
> +		--target /root/bin/$(DFGET_ARCHIVE_PREFIX).linux_amd64.rpm
The examples above are all binary files, not rpm files, I think it's OK to use "-" for binary files, and there's no "name-version-release" format.

2022-06-01 02:58 UTC, gaius-qi commented on Makefile
> +		--target /root/bin/$(DFGET_ARCHIVE_PREFIX).linux_amd64.rpm
Refer to https://github.com/golangci/golangci-lint/releases, https://github.com/dosco/graphjin/releases, https://github.com/determined-ai/determined/releases

2022-06-27 12:47 UTC, closed without merging