fix: count error & totalPage error (#1373)
dragonflyoss/Dragonfly2 pull request #1376
Opened 2022-06-13 10:48 UTC by LetFu

Signed-off-by: LetFu <letfu@outlook.com>

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-06-13 13:59 UTC, LetFu commented
> Please rebase main branch.

Ok, I've rebase, please review, thx.

2022-06-15 04:03 UTC, gaius-qi requested changes

2022-06-15 04:03 UTC, gaius-qi commented on manager/handlers/handlers.go
>  	if totalPage == 0 {
This part of the code can be deleted.

2022-06-15 04:17 UTC, LetFu commented on manager/handlers/handlers.go
>  	if totalPage == 0 {
Ok, it's deleted

2022-06-15 04:21 UTC, gaius-qi approved these changes
LGTM

2022-06-15 04:32 UTC, hyy0322 approved these changes
LGTM

2022-06-15 05:26 UTC, merged