fix Spelling errors
dragonflyoss/Dragonfly2 pull request #1430
Opened 2022-07-04 06:59 UTC by 1037husterljx

Signed-off-by: ljx373327 <ljx373327@alibaba-inc.com>

## Description
fix Spelling errors

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-07-04 07:23 UTC, gaius-qi submitted a review, later dismissed
LGTM

2022-07-05 08:42 UTC, bigerous approved these changes
LGTM

2022-07-05 08:48 UTC, gaius-qi requested changes

2022-07-05 11:51 UTC, gaius-qi approved these changes
LGTM

2022-07-05 11:56 UTC, bigerous approved these changes

2022-07-05 12:04 UTC, merged