[WIP]pipeline with linear
dragonflyoss/Dragonfly2 pull request #1555
Opened 2022-08-12 03:12 UTC by wd665544

## Description
[WIP]pipeline with linear

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-08-13 13:45 UTC, yxxhero commented
@wd665544 Please add more test for your PR.

2022-10-26 03:35 UTC, gaius-qi requested changes

2022-10-26 03:35 UTC, gaius-qi commented on manager/rpcserver/rpcserver.go
> +	logger.Infof("getModel req model id is %v", req.ModelId)
Remove log.

2022-10-26 03:35 UTC, gaius-qi commented on manager/rpcserver/rpcserver.go
> +	logger.Infof("getModel req model schid is %v", req.SchedulerId)
Remove log.

2022-10-26 03:35 UTC, gaius-qi commented on manager/rpcserver/rpcserver.go
> +	err = json.Unmarshal([]byte(result), &model)
```go
if err := xxx; err != nil {
}
```

2022-10-26 03:35 UTC, gaius-qi commented on manager/rpcserver/rpcserver.go
> +	result, err := s.rdb.Get(ctx, cache.MakeModelVersionKey(scheduler.SchedulerClusterID, scheduler.HostName, scheduler.IP, req.ModelId, req.VersionId)).Result()
```go
modelVersion, err := xxx
```

2022-10-26 03:35 UTC, gaius-qi commented on manager/rpcserver/rpcserver.go
> +	result, err := s.rdb.Get(ctx, cache.MakeModelKey(scheduler.SchedulerClusterID, scheduler.HostName, scheduler.IP, req.ModelId)).Result()
```go
model, err := xxx
```

2022-10-26 03:35 UTC, gaius-qi commented on manager/rpcserver/rpcserver.go
> +	logger.Infof("getmodelverison get result, result is %v", result)
Remove log.

2022-10-26 03:35 UTC, gaius-qi commented on manager/rpcserver/rpcserver.go
> +	err = json.Unmarshal([]byte(result), &modelVersion)
```go
if err := xxx; err != nil {
}
```

2022-10-26 03:35 UTC, gaius-qi commented on pkg/pipeline/handler.go
> +// HandlerFunc first chan represent input
Syntax error.

2022-10-26 03:35 UTC, gaius-qi commented on pkg/pipeline/pipeline.go
> +func (p *Pipeline) handleDag(ctx context.Context, cancel context.CancelFunc, graph dag.DAG[StepConstruct], fstChannel chan *Request) chan *Request {
handleDAG

2022-10-26 03:35 UTC, gaius-qi commented on pkg/pipeline/handler.go
> +	Handler HandlerFunc
handler

2022-10-26 03:35 UTC, gaius-qi commented on pkg/pipeline/handler.go
> +	in := make(chan *Request, 10)
Use constants to record `10`.

2022-10-26 03:45 UTC, merged