chore: add source error metrics
dragonflyoss/Dragonfly2 pull request #1560
Opened 2022-08-12 07:31 UTC by jim3ma

Signed-off-by: Jim Ma <majinjing3@gmail.com>

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-08-12 07:46 UTC, bigerous requested changes

2022-08-12 07:46 UTC, bigerous commented on scheduler/service/service.go
> +						metrics.PeerTaskSourceErrorCounter.WithLabelValues(task.URLMeta.Tag, proto, "0").Inc()
Here should add a "application" label, see this pr: https://github.com/dragonflyoss/Dragonfly2/pull/1559

2022-08-30 06:11 UTC, bigerous approved these changes
LGTM

2022-08-30 06:12 UTC, gaius-qi approved these changes
LGTM

2022-08-30 06:26 UTC, merged