fix: backsource temporary error judgement
dragonflyoss/Dragonfly2 pull request #1726
Opened 2022-10-09 02:57 UTC by bigerous

Signed-off-by: bigerous <cuidajun.cdj@alibaba-inc.com>

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-10-09 03:05 UTC, gaius-qi requested changes

2022-10-09 03:05 UTC, gaius-qi commented on client/daemon/peer/piece_manager.go
> +			Temporary: response.Temporary == nil || response.Temporary(),
Add repose.Temporary to https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/source/clients/httpprotocol/http_source_client.go#L263

2022-10-09 10:46 UTC, gaius-qi submitted a review, later dismissed
LGTM

2022-10-10 03:31 UTC, gaius-qi approved these changes
LGTM

2022-10-10 03:31 UTC, jim3ma approved these changes
LGTM

2022-10-10 03:33 UTC, merged