feat: daemon call leaveHost when exit
dragonflyoss/Dragonfly2 pull request #1788
Opened 2022-10-26 09:11 UTC by bigerous

Signed-off-by: bigerous <cuidajun.cdj@alibaba-inc.com>

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2022-10-26 09:29 UTC, gaius-qi requested changes

2022-10-26 09:29 UTC, gaius-qi commented on client/daemon/daemon.go
> +			_ = cd.schedulerClient.LeaveHost(ctx, &schedulerv1.LeaveHostRequest{Id: cd.schedPeerHost.Id})
Record error log.

2022-10-26 11:57 UTC, gaius-qi requested changes

2022-10-26 11:57 UTC, gaius-qi commented on pkg/rpc/scheduler/client/client.go
> +			if err := c.leaveHost(trace.ContextWithSpan(ctx, trace.SpanFromContext(ctx)), addr, req, opts...); err != nil {
```go
c.leaveHost(ctx, addr, req, opts...)
```

2022-10-26 11:59 UTC, gaius-qi approved these changes
LGTM

2022-10-27 02:21 UTC, jim3ma approved these changes
LGTM

2022-10-27 02:23 UTC, merged