feat: add default probe configuration
dragonflyoss/Dragonfly2 pull request #2070
Opened 2023-02-13 10:11 UTC by fcgxz2003

Signed-off-by: XZ <834756128@qq.com>

Add default probe configuration.
ProbeQueueLength is the number of probes that an edge stores.
GetProbesInterval is the interval at which the host get the probe list.
AOIPriorityInterval is the priority effect of the information of age for host.
GetProbeCount is the number of targets that the scheduler sends to the host for probing.
SyncNetworkTopologyInterval is the interval at which network topologies are synchronized between schedulers.
StoreNetworkTopologyInterval is the interval at which the network topology is stored locally.

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-02-13 10:38 UTC, gaius-qi requested changes

2023-02-13 10:38 UTC, gaius-qi commented on scheduler/config/config.go
> +	Probe ProbeConfig `yaml:"probe" mapstructure:"probe"`
```golang
NetworkTopology NetworkTopologyConfig `yaml:"networkTopology" mapstructure:"networkTopology"`
```

2023-02-13 10:38 UTC, gaius-qi commented on scheduler/config/config.go
> +type ProbeConfig struct {
```golang
type NetworkTopologyConfig struct {
   Probe ProbeConfig `yaml:"probe" mapstructure:"probe"`
}

type ProbeConfig struct {
}
```

2023-02-13 12:22 UTC, gaius-qi requested changes

2023-02-13 12:22 UTC, gaius-qi commented on scheduler/config/config.go
> +	ProbeQueueLength int `mapstructure:"probeQueueLength" yaml:"probeQueueLength"`
`ProbeQueueLength` => `QueueLength`

2023-02-13 12:22 UTC, gaius-qi commented on scheduler/config/config.go
> +	AOIPriorityInterval time.Duration `mapstructure:"AOIPriorityInterval" yaml:"AOIPriorityInterval"`
Remove `AOIPriorityInterval`.

2023-02-13 12:22 UTC, gaius-qi commented on scheduler/config/config.go
> +	StoreNetworkTopologyInterval time.Duration `mapstructure:"storeNetworkTopologyInterval" yaml:"storeNetworkTopologyInterval"`
`StoreNetworkTopologyInterval` => `CollectInterval`

2023-02-13 12:22 UTC, gaius-qi commented on scheduler/config/config.go
> +	GetProbesInterval time.Duration `mapstructure:"getProbesInterval" yaml:"getProbesInterval"`
`GetProbesInterval` => `SyncInterval`

2023-02-13 12:22 UTC, gaius-qi commented on scheduler/config/config.go
> +	GetProbeCount int `mapstructure:"getProbeCount" yaml:"getProbeCount"`
`GetProbeCount` => `SyncCount`

2023-02-14 09:09 UTC, gaius-qi requested changes

2023-02-14 09:09 UTC, gaius-qi commented on scheduler/config/config.go
> +	// QueueLength is the maximum number of probes that an edge stores.
QueueLength is the length of probe queue in directed graph.

2023-02-14 09:09 UTC, gaius-qi commented on scheduler/config/config.go
>  type ProbeConfig struct {
Add `Enable` params to `ProbeConfig`.

2023-02-14 09:09 UTC, gaius-qi commented on scheduler/config/constants.go
> +	DefaultCollectInterval = 60 * time.Second
```go
// DefaultNetworkTopologyCollectInterval is the default interval of collecting network topology.
DefaultNetworkTopologyCollectInterval = 60 * time.Second
```

2023-02-14 09:09 UTC, gaius-qi commented on scheduler/config/constants.go
> +	DefaultSyncNetworkTopologyInterval = 30 * time.Second
```go
// DefaultNetworkTopologySyncInterval is the default interval of synchronizing network topology between schedulers.
DefaultNetworkTopologySyncInterval = 30 * time.Second
```

2023-02-14 09:09 UTC, gaius-qi commented on scheduler/config/constants.go
> +	// DefaultQueueLength is the default maximum number of probes that an edge stores.
```go
// DefaultProbeQueueLength is the default length of probe queue in directed graph.
DefaultProbeQueueLength = 5
```

2023-02-14 09:09 UTC, gaius-qi commented on scheduler/config/constants.go
> +	DefaultSyncProbesInterval = 30 * time.Second
```go
// DefaultProbeSyncInterval is the default interval of synchronizing host's probes.
DefaultProbeSyncInterval = 30 * time.Second
```

2023-02-14 09:09 UTC, gaius-qi commented on scheduler/config/constants.go
> +	DefaultSyncCount = 50
```go
// DefaultProbeSyncCount is the default number of probing hosts.
DefaultProbeSyncCount = 50
```

2023-02-15 09:53 UTC, gaius-qi requested changes

2023-02-15 09:53 UTC, gaius-qi commented on scheduler/config/config.go
> +	// Enable networkTopology services, including probe, network topology collection and synchronization service.
`Enable network topology services, including probe, network topology collection and synchronization service.`

2023-02-15 10:06 UTC, gaius-qi approved these changes
LGTM

2023-02-15 10:09 UTC, yxxhero approved these changes

2023-02-15 10:21 UTC, merged