refactor: improve the performance of the code
dragonflyoss/Dragonfly2 pull request #2162
Opened 2023-03-13 09:57 UTC by zhouhao3

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-03-13 10:27 UTC, gaius-qi requested changes

2023-03-13 10:27 UTC, gaius-qi commented on pkg/net/url/url.go
> +	filterMap := make(map[string]bool)
`hidden := make(map[string]struct{})`

2023-03-14 01:09 UTC, zhouhao3 commented on pkg/net/url/url.go
> +	filterMap := make(map[string]bool)
Done, thanks.

2023-03-14 02:38 UTC, gaius-qi approved these changes
LGTM

2023-03-14 02:38 UTC, merged