refactor cmd
dragonflyoss/Dragonfly2 pull request #217
Opened 2021-05-12 03:49 UTC by garfield009

## Description

## Related Issue
#175 

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-05-12 10:11 UTC, gaius-qi requested changes

2021-05-12 10:11 UTC, gaius-qi commented on client/dfget/dfget.go
> +	// todo showBar为true才使用
Use English

2021-05-12 10:11 UTC, gaius-qi commented on cmd/cdn/cmd/root.go
> +	ff := common.InitMonitor(cfg.Verbose, cfg.PProfPort, cfg.Jaeger)
What is `ff`?

2021-05-12 10:11 UTC, gaius-qi commented on cmd/common/common.go
> +	if !isCommonFlagsBind {
Why use `isCommonFlagsBind`?

2021-05-12 10:11 UTC, gaius-qi commented on cmd/common/common.go
> +		if useConfigFile {
Why use `useConfigFile` ?

2021-05-12 10:11 UTC, gaius-qi commented on cmd/common/common.go
> +	if !cmd.HasParent() {
Why use `cmd.HasParent`?

2021-05-12 10:11 UTC, gaius-qi commented on cmd/common/common.go
> +	if useConfigFile && !isConfigFileRead {
Why use `useConfigFile` & `isConfigFileRead`?

2021-05-12 10:11 UTC, gaius-qi commented on pkg/rpc/dfdaemon/client/client.go
>  	// 生成taskId
Use English

2021-05-13 03:26 UTC, ansinlee approved these changes

2021-05-17 13:33 UTC, 244372610 approved these changes

2021-05-17 13:38 UTC, ansinlee submitted a review, later dismissed

2021-05-17 13:45 UTC, garfield009 commented on cmd/cdn/cmd/root.go
> +	ff := common.InitMonitor(cfg.Verbose, cfg.PProfPort, cfg.Jaeger)
final function

2021-05-17 13:46 UTC, 244372610 submitted a review, later dismissed

2021-05-17 13:51 UTC, 244372610 approved these changes

2021-05-17 13:51 UTC, ansinlee approved these changes

2021-05-17 13:56 UTC, merged