feat: add trainer configuration
dragonflyoss/Dragonfly2 pull request #2216
Opened 2023-03-24 05:30 UTC by MIchaelFU0403

Add trainer configuration
## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-03-24 07:00 UTC, zhoulizhen commented on trainer/config/config.go
> +	// Metrics configuration
// Metrics configuration.

2023-03-24 07:00 UTC, zhoulizhen commented on trainer/config/config.go
> +	// Train configuration
// Train configuration.

2023-03-24 07:00 UTC, zhoulizhen commented on trainer/config/config.go
> +// New default configuration
// New default configuration.

2023-03-27 03:18 UTC, gaius-qi requested changes

2023-03-27 03:18 UTC, gaius-qi commented on trainer/config/config.go
> +	PortRange TCPListenPortRange `yaml:"port" mapstructure:"port"`
Use `Port int`.

2023-03-27 03:18 UTC, gaius-qi commented on trainer/config/config.go
> +	// AdvertiseIP is advertise ip.
Add `AdvertiseIP`.

2023-03-27 03:18 UTC, gaius-qi commented on trainer/config/config.go
> +type ObjectStorageConfig struct {
Remove `ObjectStorageConfig`.

2023-03-27 03:18 UTC, gaius-qi commented on trainer/config/config.go
> +	KeepAlive KeepAliveConfig `yaml:"keepAlive" mapstructure:"keepAlive"`
Remove `KeepAlive`.

2023-04-03 02:59 UTC, gaius-qi requested changes

2023-04-03 02:59 UTC, gaius-qi commented on trainer/config/constants.go
> +	DefaultCertDNSNames = []string{"dragonfly-scheduler", "dragonfly-scheduler.dragonfly-system.svc", "dragonfly-scheduler.dragonfly-system.svc.cluster.local"}
Rename `dragonfly-scheduler` to `dragonfly-trainer`.

2023-04-03 02:59 UTC, gaius-qi commented on trainer/config/testdata/trainer.yaml
> +
Remove black line.

2023-04-03 06:08 UTC, gaius-qi approved these changes
LGTM

2023-04-03 06:09 UTC, merged