feat: scheduler adds trainer
dragonflyoss/Dragonfly2 pull request #2319
Opened 2023-05-05 03:13 UTC by MinH-09

Trainer in scheduler is responsible for transferring data to trainer for training model
## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-05-05 12:00 UTC, fcgxz2003 commented on scheduler/trainer/trainer_test.go
> +				gomock.InOrder(
Only one mock that does not require gomock.Inorder.

2023-05-05 12:18 UTC, fcgxz2003 commented on scheduler/trainer/trainer.go
> +	download, err := t.storage.ListDownload()
downloads

2023-05-05 12:18 UTC, fcgxz2003 commented on scheduler/trainer/trainer.go
> +	networkTopology, err := t.storage.ListNetworkTopology()
networkTopologies

2023-05-05 12:19 UTC, fcgxz2003 commented on scheduler/trainer/trainer.go
> +	for _, data := range download {
for _, download := range downloads {

2023-05-05 12:19 UTC, fcgxz2003 commented on scheduler/trainer/trainer.go
> +	for _, data := range networkTopology {
for _, networkTopology := range networkTopologies {

2023-05-05 12:48 UTC, fcgxz2003 commented on scheduler/trainer/trainer_test.go
> +				mts.Send(gomock.Any()).DoAndReturn(
delete

2023-05-05 12:48 UTC, fcgxz2003 commented on scheduler/trainer/trainer_test.go
> +				mts.Send(gomock.Any()).DoAndReturn(
.AnyTimes()

2023-05-05 12:48 UTC, fcgxz2003 commented on scheduler/trainer/trainer_test.go
> +				md.GetScheduler().Return(nil, nil)
md.GetScheduler().Return(&managerv2.Scheduler{
					Hostname: "foo",
					Ip:       "127.0.0.1",
					SchedulerCluster: &managerv2.SchedulerCluster{
						Id: 1,
					},
				}, nil)

2023-05-09 03:17 UTC, gaius-qi requested changes

2023-05-09 03:17 UTC, gaius-qi commented on scheduler/announcer/announcer.go
> +	if a.config.Trainer.Enable {
Remove.

2023-05-17 12:13 UTC, fcgxz2003 commented on scheduler/announcer/announcer.go
> +		if err == io.EOF || n == 0 {
remove n==0

2023-05-17 12:15 UTC, fcgxz2003 commented on scheduler/announcer/announcer.go
> +		if err == io.EOF || n == 0 {
remove n==0

2023-05-17 12:17 UTC, fcgxz2003 commented on scheduler/announcer/announcer.go
> +		}
`if err == io.EOF {
	break
}
if err != nil {
	return err
}`

2023-05-17 12:18 UTC, fcgxz2003 commented on scheduler/announcer/announcer.go
> +		}
`if err == io.EOF {
	break
}
if err != nil {
	return err
}`

2023-05-18 02:03 UTC, zhoulizhen commented on scheduler/scheduler.go
> +	// trainer client.
// Trainer client.

2023-05-18 06:21 UTC, fcgxz2003 reviewed
LGTM

2023-05-18 06:48 UTC, MIchaelFU0403 reviewed
LGTM

2023-05-18 09:13 UTC, gaius-qi requested changes

2023-05-18 09:13 UTC, gaius-qi commented on scheduler/announcer/announcer.go
> +func (a *announcer) announceToTrainer() {
https://github.com/dragonflyoss/Dragonfly2/blob/main/client/daemon/announcer/announcer.go

2023-05-22 02:32 UTC, fcgxz2003 reviewed
LGTM

2023-05-22 10:10 UTC, gaius-qi requested changes

2023-05-22 10:10 UTC, gaius-qi commented on scheduler/announcer/announcer.go
> +	if a.trainerClient != nil {
Move to announceToManager back.

2023-05-23 01:26 UTC, closed without merging