[WIP]feat:add storage for trainer
dragonflyoss/Dragonfly2 pull request #2411
Opened 2023-05-31 08:00 UTC by MIchaelFU0403

Add storage for trainer.
## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-05-31 08:39 UTC, zhoulizhen commented on trainer/storage/storage.go
> +// ClearNetworkTopology removes all files.
// Clear removes all files.

2023-05-31 08:39 UTC, zhoulizhen commented on trainer/storage/types.go
> +// Error co0ntains content for error.
// Error contains content for error.

2023-05-31 08:39 UTC, zhoulizhen commented on trainer/storage/types.go
> +	// Message is thzxre message of error.
// Message is the message of error.

2023-06-01 03:41 UTC, gaius-qi requested changes

2023-06-01 03:41 UTC, gaius-qi commented on trainer/storage/storage.go
> + *     Copyright 2022 The Dragonfly Authors
`Copyright 2023 The Dragonfly Authors`

2023-06-05 14:11 UTC, closed without merging