Fix issues in the objectstorage based on JuiceFS use cases.
dragonflyoss/Dragonfly2 pull request #2648
Opened 2023-08-17 08:42 UTC by XDTD

## Description

"Fixing issues in the object storage based on JuiceFS use cases. Mainly includes:

1. Route path of createbucket.
2. Unable to properly pass objectkey when calling copyobject.
3. Oss GetObjectMeta return not found error.
4. getObjectMetadatas does not include directories.

## Related Issue
#2176 

## Motivation and Context

To provide support for JuiceFS objectStorage implementation.
## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-08-17 09:46 UTC, gaius-qi requested changes

2023-08-17 09:46 UTC, gaius-qi commented on client/daemon/objectstorage/objectstorage.go
> +	logger.Infof("put object to %s", objectKey)
Remove log.

2023-08-17 09:46 UTC, gaius-qi commented on pkg/objectstorage/oss.go
> +	if limit == 0 || limit > DefaultGetObjectMetadatasLimit {
Remove `|| limit > DefaultGetObjectMetadatasLimit`.

2023-08-29 11:54 UTC, XDTD commented on client/daemon/objectstorage/objectstorage.go
> +	logger.Infof("put object to %s", objectKey)
done

2023-08-29 11:54 UTC, XDTD commented on pkg/objectstorage/oss.go
> +	if limit == 0 || limit > DefaultGetObjectMetadatasLimit {
done

2023-08-29 12:33 UTC, gaius-qi requested changes
Add default httpclient.

2023-08-30 03:19 UTC, gaius-qi approved these changes
LGTM

2023-08-30 03:20 UTC, merged