Add go-cache as local cache, add redis as distributed
dragonflyoss/Dragonfly2 pull request #272
Opened 2021-05-28 07:00 UTC by yangjun289519474

…cache, add lease based on mysql as manager keepalive owner

Signed-off-by: hanson.yj <hanson.yj@alibaba-inc.com>

Add go-cache as local cache, add redis as distributed

## Description

Add go-cache as local cache, let scheduler cluster, scheduler instance, cdn cluster, cdn instance have TTL function;
Add redis as distributed cache, and store keepalive time of scheduler instance and cdn instance between managers;
Add lease based mysql, and lease owner decide the background keepalive goroute;

## Related Issue

#270 

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [x] Code compiles correctly.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-05-28 07:33 UTC, gaius-qi requested changes

2021-05-28 07:33 UTC, gaius-qi commented on manager/config/mock_config.go
> +package config
Remove this file.

2021-05-28 07:34 UTC, gaius-qi commented
The pull request needs to supplement the unit test cases.

2021-06-01 04:02 UTC, 244372610 commented on manager/configsvc/service.go
> +		if instance, exist := svc.cdnInstances.Get(instanceID); exist {
For the moment, change to the GetWithExpiration method

2021-06-01 09:15 UTC, 244372610 approved these changes

2021-06-03 02:57 UTC, gaius-qi approved these changes

2021-06-03 02:57 UTC, merged