Optimized dfstore upload file performance
dragonflyoss/Dragonfly2 pull request #2803
Opened 2023-10-16 09:37 UTC by Yong-An9

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-10-16 09:39 UTC, Yong-An9 commented
![image](https://github.com/dragonflyoss/Dragonfly2/assets/68688662/df80da06-913c-4ad9-a45e-e12751bc0d19)

2023-10-16 10:00 UTC, Yong-An9 commented
Performance comparison before and after optimization：
![image](https://github.com/dragonflyoss/Dragonfly2/assets/68688662/d69361ec-3198-407e-a7dc-4b6f9a80fcf2)

2023-10-16 10:01 UTC, gaius-qi requested changes

2023-10-16 10:01 UTC, gaius-qi commented on client/dfstore/dfstore.go
> +	buf := make([]byte, 256*1024*1024)
Why use 256M?

2023-10-16 11:20 UTC, Yong-An9 commented on client/dfstore/dfstore.go
> +	buf := make([]byte, 256*1024*1024)
Aready tried the 4m 8m 16M 32M case  and found that the larger the buffer, the faster the speed. Consider putting this value in the configuration file?
4M:
![企业微信截图_360e4220-5aca-4755-86d5-b2d4dd1b8380](https://github.com/dragonflyoss/Dragonfly2/assets/68688662/ca396418-606d-464c-8656-4689dd5aad5b)

8M:
![企业微信截图_7b33e289-ce16-4dc1-a6d6-f2538fb60531](https://github.com/dragonflyoss/Dragonfly2/assets/68688662/910cbf3e-d76b-4a73-91bf-b251242d7ff1)
16M:
![企业微信截图_dadc923b-d4fa-4430-9f60-602d3925bb08](https://github.com/dragonflyoss/Dragonfly2/assets/68688662/b00c5a50-caed-4fad-94d0-8d1f87226a97)
32M:
![企业微信截图_68dfaef3-a232-4123-9f90-b83f4ed24bc4](https://github.com/dragonflyoss/Dragonfly2/assets/68688662/bb5aec44-ada8-458e-94fd-662d7807cc4c)

2023-10-16 11:34 UTC, Yong-An9 commented on client/dfstore/dfstore.go
> +	buf := make([]byte, 256*1024*1024)
64M:
![企业微信截图_9cfc83e9-0c30-4071-8fed-63dd8a95d592](https://github.com/dragonflyoss/Dragonfly2/assets/68688662/6d308e42-d8b7-40f5-95db-3c02d8f5e59a)

2023-10-16 11:43 UTC, gaius-qi submitted a review, later dismissed
LGTM

2023-10-17 03:33 UTC, gaius-qi approved these changes
LGTM

2023-10-17 03:34 UTC, merged