feat: add unit tests for manager handlers
dragonflyoss/Dragonfly2 pull request #3202
Opened 2024-04-17 14:56 UTC by BruceAko

## Description

Add unit tests for manager handlers.

## Related Issue

fix https://github.com/dragonflyoss/Dragonfly2/issues/2705

## Motivation and Context

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2024-04-17 15:05 UTC, BruceAko commented
@gaius-qi So far I've written unit tests for `application.go`, could you please review this part of the code so that I can make sure I'm writing the unit tests in the right way? Thank you very much :)

2024-04-18 03:16 UTC, gaius-qi commented
> @gaius-qi So far I've written unit tests for `application.go`, could you please review this part of the code so that I can make sure I'm writing the unit tests in the right way? Thank you very much :)

@BruceAko I think it is good！

2024-04-18 06:32 UTC, gaius-qi commented
@BruceAko Please fix CI.

2024-04-19 06:11 UTC, gaius-qi commented
@BruceAko Have you finished PR?

2024-04-21 18:10 UTC, BruceAko commented
@gaius-qi I have finished PR now. Please take a look.

2024-04-22 02:47 UTC, gaius-qi requested changes

2024-04-22 02:47 UTC, gaius-qi commented on manager/handlers/application_test.go
> +				assert.Equal(w.Body.String(), mockApplicationResponseBody)
Unmarshal `w.Body.String()` to struct, remove `mockApplicationReqBody`.

```golang
application := models.Application{}
if err := json.Unmarshal(...) {
...
}

assert.Equal(resp, models.Application{...})
```

Please modify the same type of cases.

2024-04-22 02:47 UTC, gaius-qi commented on manager/handlers/application_test.go
> +			req:  httptest.NewRequest("POST", "/api/v1/applications", nil),
Replace `POST` with `http.MethodPost`.

2024-04-22 02:48 UTC, gaius-qi commented
@BruceAko Can you add unit tests for `handlers.go` in next PR? Thx

2024-04-22 05:23 UTC, BruceAko commented
> @BruceAko Can you add unit tests for `�handlers.go` in next PR? Thx

@gaius-qi Ok, sure. And I fixed the changes you raised in two new commits, PTAL.

2024-04-22 09:42 UTC, merged