Worker pool pattern
dragonflyoss/Dragonfly2 pull request #342
Opened 2021-06-15 08:21 UTC by 244372610

## Description
The unbuffered channel is used to create a pool of goroutines that perform and control a set of tasks that are executed concurrently and are used in the write file task of the CDN download file

## Related Issue
fix #334 

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-15 09:12 UTC, gaius-qi requested changes

2021-06-15 09:12 UTC, gaius-qi commented on pkg/sync/work/work.go
> +	for i := 0; i < maxGoroutines; i++ {
Use `sync/semaphore`.

2021-06-17 12:01 UTC, gaius-qi approved these changes

2021-06-21 08:34 UTC, jim3ma approved these changes
LGTM

2021-06-21 09:12 UTC, ansinlee approved these changes

2021-06-21 09:14 UTC, merged