Modify source client operations
dragonflyoss/Dragonfly2 pull request #361
Opened 2021-06-22 12:38 UTC by 244372610

Signed-off-by: santong <weipeng.swp@alibaba-inc.com>

## Description
add header information for the source
add lastmodified timestamp of resource

## Related Issue
fix #360 

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-22 12:52 UTC, jim3ma commented on pkg/source/headers.go
> +	ETag         = "ETag"
LastModified has been defined in "github.com/go-http-utils/headers".
Just use headers package.

2021-06-22 12:55 UTC, Louhwz commented on pkg/source/hdfsprotocol/hdfs_source_client.go
> +func init() {
既然已经定了规范，就还是显示初始化吧

2021-06-22 13:05 UTC, gaius-qi requested changes

2021-06-22 13:05 UTC, gaius-qi commented on pkg/source/headers.go
> +type RequestHeader map[string]string
Requestheader and Responseheader are duplicated

2021-06-22 13:05 UTC, 244372610 commented on pkg/source/hdfsprotocol/hdfs_source_client.go
> +func init() {
你指的是代码规约吗？这个地方满足规范的。如果不放在这你觉得应该放在哪里

2021-06-22 13:14 UTC, Louhwz commented on pkg/source/hdfsprotocol/hdfs_source_client.go
> +func init() {
> 你指的是代码规约吗？这个地方满足规范的。如果不放在这你觉得应该放在哪里
这条跟“避免使用 init()“相悖呀。
可以在source目录下有个统一的Init函数（注意大写），这个Init函数里面调用每个source的Init函数。外部再有个地方调用source下的Init函数

2021-06-22 13:23 UTC, 244372610 commented on pkg/source/hdfsprotocol/hdfs_source_client.go
> +func init() {
这样会构成循环依赖哟

2021-06-22 13:24 UTC, 244372610 commented on pkg/source/hdfsprotocol/hdfs_source_client.go
> +func init() {
> > 你指的是代码规约吗？这个地方满足规范的。如果不放在这你觉得应该放在哪里
> 
> 这条跟“避免使用 init()“相悖呀。
> 可以在source目录下有个统一的Init函数（注意大写），这个Init函数里面调用每个source的Init函数。外部再有个地方调用source下的Init函数

这样会构成循环依赖哟

2021-06-22 13:26 UTC, 244372610 commented on pkg/source/hdfsprotocol/hdfs_source_client.go
> +func init() {
而且文档中说的是避免使用，不是不让使用。我理解init方法就是做初始化操作的

2021-06-23 02:13 UTC, Louhwz commented on pkg/source/hdfsprotocol/hdfs_source_client.go
> +func init() {
> > > 你指的是代码规约吗？这个地方满足规范的。如果不放在这你觉得应该放在哪里
> > 
> > 
> > 这条跟“避免使用 init()“相悖呀。
> > 可以在source目录下有个统一的Init函数（注意大写），这个Init函数里面调用每个source的Init函数。外部再有个地方调用source下的Init函数
> 
> 这样会构成循环依赖哟

emmm，仔细看了一下，虽然也可以避免循环依赖，但那样改动就比较大了。然后无论是单测还是引用都还没想出什么问题，这个comment可以resolve了。谢谢你的讨论。

2021-06-23 06:11 UTC, ansinlee approved these changes

2021-06-23 06:15 UTC, gaius-qi approved these changes

2021-06-23 06:16 UTC, merged