[WIP] Refactor manager
dragonflyoss/Dragonfly2 pull request #363
Opened 2021-06-22 13:10 UTC by gaius-qi

## Description
- Refactor manager

## Related Issue
Fixes #362 

## Motivation and Context
N/A

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [x] Code compiles correctly.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-06-29 15:14 UTC, yxxhero requested changes

2021-06-30 04:12 UTC, garfield009 approved these changes

2021-06-30 04:34 UTC, yxxhero approved these changes
LGTM

2021-06-30 06:19 UTC, 244372610 approved these changes

2021-06-30 06:38 UTC, merged