[WIP] Refactor scheduler task management
dragonflyoss/Dragonfly2 pull request #369
Opened 2021-06-23 09:47 UTC by 244372610

## Description

## Related Issue
fix #366 

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-13 02:40 UTC, jim3ma commented on internal/idgen/uuid.go
> +	return fmt.Sprintf("%s-%d_CDN", cdnHostName, serverPort)
Where is uuid ?

2021-07-13 02:54 UTC, gaius-qi requested changes

2021-07-13 02:54 UTC, gaius-qi commented on scheduler/daemon/gc/manager.go
> +func (m *manager) StartGC(ctx context.Context) error {
Use `pkg/gc` library.

2021-07-13 02:54 UTC, gaius-qi commented on scheduler/daemon/host/host_manager.go
> +/*
Unified naming scheduler/daemon/host/host_manager.go and scheduler/daemon/host_mgr.go

2021-07-22 02:05 UTC, jim3ma commented on tmp
> +<!DOCTYPE html><!--STATUS OK-->
Unused file.

2021-07-22 02:07 UTC, jim3ma commented on docs/en/config/dfget.yaml
> +dataDir: /Users/sunweipeng1/dragonfly
Reset config.

2021-07-22 02:07 UTC, jim3ma commented on docs/en/config/dfget.yaml
> +workHome: /Users/sunweipeng1/dragonfly
Reset config.

2021-07-22 02:08 UTC, jim3ma commented on pkg/rpc/scheduler/scheduler.proto
> +  // todo what effect
`todo` -> `TODO`

2021-07-22 03:59 UTC, gaius-qi approved these changes
LGTM

2021-07-22 04:10 UTC, jim3ma approved these changes

2021-07-22 04:10 UTC, merged