Feature/dfget param
dragonflyoss/Dragonfly2 pull request #373
Opened 2021-06-25 11:15 UTC by garfield009

## Description
adjust dfget grpc param

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-25 11:26 UTC, 244372610 approved these changes

2021-06-25 11:38 UTC, 244372610 commented on internal/rpc/dfdaemon/dfdaemon.proto
> +  string output = 3;
add ratelimit param ?

2021-06-25 13:22 UTC, gaius-qi requested changes

2021-06-25 13:22 UTC, gaius-qi commented on internal/rpc/dfdaemon/dfdaemon.proto
> +  int64 uid = 9;
Use `uint64`.

2021-06-25 13:22 UTC, gaius-qi commented on internal/rpc/dfdaemon/dfdaemon.proto
> +  int64 gid = 10;
Use `uint64`.

2021-06-28 01:54 UTC, garfield009 commented on internal/rpc/dfdaemon/dfdaemon.proto
> +  int64 uid = 9;
no need change it, interface need int64

2021-06-28 01:54 UTC, garfield009 commented on internal/rpc/dfdaemon/dfdaemon.proto
> +  int64 gid = 10;
no need change it, interface need int64

2021-06-28 02:24 UTC, gaius-qi approved these changes

2021-06-28 02:24 UTC, merged