Update kustomize default namespace and images
dragonflyoss/Dragonfly2 pull request #389
Opened 2021-06-30 12:38 UTC by jim3ma

Signed-off-by: Jim Ma <majinjing3@gmail.com>

## Description

Update kustomize default namespace and images

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-30 12:39 UTC, 244372610 submitted a review, later dismissed

2021-06-30 12:40 UTC, gaius-qi requested changes

2021-06-30 12:40 UTC, gaius-qi commented on deploy/kustomize/single-cluster-openkruise/bases/kustomization.yaml
> +  newTag: v0.1.0-alpha.1
Use `v0.1.0-beta` tag.

2021-06-30 13:31 UTC, gaius-qi approved these changes
LGTM

2021-07-01 06:33 UTC, xujihui1985 approved these changes

2021-07-01 06:34 UTC, merged