Feature: update helm chart images tag to v0.1.0.beta
dragonflyoss/Dragonfly2 pull request #395
Opened 2021-07-01 03:40 UTC by jim3ma

Signed-off-by: Jim Ma <majinjing3@gmail.com>

## Description

Update helm chart images tag to v0.1.0.beta

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-01 05:22 UTC, yxxhero requested changes

2021-07-01 05:22 UTC, yxxhero commented on deploy/charts/dragonfly/templates/namespace.yaml
> +{{ if eq $.Values.installation.namespace "kube-system" }}
```yaml
{{ if ne $.Values.installation.namespace "kube-system" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.installation.namespace }}
{{ end }}
```

2021-07-01 06:40 UTC, gaius-qi submitted a review, later dismissed
LGTM

2021-07-01 07:04 UTC, yxxhero approved these changes
LGTM

2021-07-01 07:28 UTC, gaius-qi approved these changes

2021-07-01 07:35 UTC, xujihui1985 approved these changes

2021-07-01 07:36 UTC, merged

2025-04-15 10:43 UTC, Liam-Zhao reviewed
LGTM