[WIP] Add E2E tests and workflow
dragonflyoss/Dragonfly2 pull request #402
Opened 2021-07-02 03:26 UTC by gaius-qi

## Description
- Add E2E tests.
- Add E2E workflow.

## Related Issue
#330 

## Motivation and Context
N/A

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [x] Code compiles correctly.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-02 04:00 UTC, jim3ma requested changes

2021-07-02 10:28 UTC, jim3ma commented on .github/workflows/e2e.yml
> +      - name: Wait for running
List pods for debugging.

2021-07-05 01:34 UTC, jim3ma commented on .github/workflows/e2e.yml
> +          make docker-build-manager
use `make docker-build` instead.

2021-07-08 13:03 UTC, garfield009 approved these changes

2021-07-08 13:10 UTC, jim3ma commented on test/testdata/containerd/config.toml
> +          endpoint = ["http://10.15.233.88:65001"]
`endpoint = ["http://10.15.233.88:65001"]` -> `endpoint = ["http://127.0.0.1:65001"]`

2021-07-08 13:55 UTC, jim3ma approved these changes

2021-07-08 14:06 UTC, 244372610 approved these changes

2021-07-08 14:07 UTC, merged