[WIP]Manager user logic.
dragonflyoss/Dragonfly2 pull request #419
Opened 2021-07-04 02:45 UTC by yxxhero

Signed-off-by: yxxhero <aiopsclub@163.com>

## Description
Manager user logic.

## Related Issue
link: https://github.com/dragonflyoss/Dragonfly2/issues/376

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-05 03:57 UTC, gaius-qi requested changes

2021-07-05 03:57 UTC, gaius-qi commented on manager/server/router.go
> +	ai := apiv1.Group("/auth")
Use path `api/v1/user`.

2021-07-05 03:57 UTC, gaius-qi commented on manager/service/user.go
> +	avatar := ""
Remove setting the default avatar, fill the default avatar on the frontend.

2021-07-05 03:57 UTC, gaius-qi commented on manager/types/user.go
> +	Phone    string `form:"phone" binding:"required"`
User `omitempty`.

2021-07-05 03:57 UTC, gaius-qi commented on manager/service/user.go
> +	encryptedPassword := digestutils.Sha256(json.Password, passwordSalt)
Use `bcrypt.GenerateFromPassword`.

2021-07-05 03:57 UTC, gaius-qi commented on manager/service/user.go
> +	if digestutils.Sha256(json.Password, user.PasswordSalt) != user.EncryptedPassword {
Use `bcrypt.CompareHashAndPassword`.

2021-07-05 03:57 UTC, gaius-qi commented on manager/model/user.go
> +	PasswordSalt      string `gorm:"column:password;size:256;not null" json:"password"`
Remove `PasswordSalt`.
Refer to https://medium.com/@jcox250/password-hash-salt-using-golang-b041dc94cb72

2021-07-07 01:20 UTC, yxxhero commented
@gaius-qi ping

2021-07-07 09:27 UTC, gaius-qi submitted a review, later dismissed

2021-07-07 09:27 UTC, gaius-qi commented on manager/model/user.go
> +	EncryptedPassword string `gorm:"column:encrypted_password;size:1024" json:"encrypted_password"`
Remove `json:"encrypted_password"`

2021-07-07 09:27 UTC, gaius-qi commented on manager/handlers/user.go
> +	ctx.JSON(http.StatusOK, userInfo)
Remove user model's `json:"encrypted_password"` and return userInfo directly.

2021-07-08 02:33 UTC, gaius-qi approved these changes

2021-07-08 12:42 UTC, garfield009 approved these changes

2021-07-08 12:56 UTC, merged