[WIP] add rbac support.
dragonflyoss/Dragonfly2 pull request #474
Opened 2021-07-18 04:05 UTC by yxxhero

Signed-off-by: yxxhero <aiopsclub@163.com>

## Description
add rbac support

## Related Issue
https://github.com/dragonflyoss/Dragonfly2/issues/376

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-19 02:52 UTC, gaius-qi requested changes

2021-07-19 02:52 UTC, gaius-qi commented on manager/database/database.go
> +func initAdminUser(db *gorm.DB) error {
Put it in the `seed` function.

2021-07-19 02:52 UTC, gaius-qi commented on manager/database/database.go
> +	err := db.Where("name = ?", adminUserName).First(&user).Error
Use `Count()` api.

2021-07-19 02:52 UTC, gaius-qi commented on manager/handlers/rbac.go
> +// @Router /permission [post]
Use `delete` action.

2021-07-19 02:52 UTC, gaius-qi commented on manager/service/service.go
> +func GetRestDB(r REST) (*gorm.DB, error) {
Remove `GetRestDB`.

2021-07-19 02:52 UTC, gaius-qi commented on manager/middlewares/rbac.go
> +	gdb, err := service.GetRestDB(r)
Get database from `database` package.

2021-07-19 02:52 UTC, gaius-qi commented on manager/server/router.go
> +	pn.DELETE("", h.DestroyPermission)
Delete permission with `ID`.

2021-07-19 12:14 UTC, gaius-qi requested changes

2021-07-19 12:14 UTC, gaius-qi commented on pkg/permission/rbac/rbac.go
> +package rbac
Move rbac package to manager.

2021-07-19 12:28 UTC, gaius-qi requested changes

2021-07-19 12:28 UTC, gaius-qi commented on manager/middlewares/rbac.go
> +	enforcer, err := rbac.NewEnforcer(gdb)
Move `NewEnforcer` to `server.New` func.

2021-07-19 12:28 UTC, gaius-qi commented on manager/middlewares/rbac.go
> +func RBAC(r service.REST) (gin.HandlerFunc, *casbin.Enforcer, error) {
`func RBAC(e *casbin.Enforcer) gin.HandlerFunc {}`

2021-07-19 12:32 UTC, gaius-qi requested changes

2021-07-19 12:32 UTC, gaius-qi commented on manager/server/router.go
> +func initRouter(verbose bool, serviceREST service.REST) (*gin.Engine, error) {
Use `servive`. `initRouter` is only used for `rest api`.

2021-07-19 12:34 UTC, gaius-qi requested changes

2021-07-19 12:34 UTC, gaius-qi commented on manager/server/router.go
> +	rbac, enforcer, err := middlewares.RBAC(serviceREST)
Use middleware like https://github.com/gin-gonic/gin#using-middleware

2021-07-29 08:07 UTC, gaius-qi requested changes

2021-07-29 08:13 UTC, gaius-qi requested changes

2021-07-29 08:13 UTC, gaius-qi commented on manager/handlers/rbac.go
> +// @Router /permission/roles/{userName} [get]
`/permission/roles/{subject}`

2021-07-29 08:13 UTC, gaius-qi commented on manager/middlewares/rbac.go
> +			c.JSON(401, gin.H{
Use `http.StatusUnauthorized `

2021-07-29 08:13 UTC, gaius-qi commented on manager/server/router.go
> +	// auto init role check roles
`Auto`

2021-08-02 07:54 UTC, gaius-qi requested changes

2021-08-02 07:54 UTC, gaius-qi commented on manager/handlers/rbac.go
> +	ctx.JSON(http.StatusOK, gin.H{"message": "create permission successfully"})
Remove message.

2021-08-02 07:54 UTC, gaius-qi commented on manager/handlers/rbac.go
> +	ctx.JSON(http.StatusOK, gin.H{"message": "destroy permission successfully"})
Remove message.

2021-08-02 11:17 UTC, gaius-qi approved these changes
LGTM

2021-08-02 11:30 UTC, gaius-qi approved these changes
LGTM

2021-08-02 12:04 UTC, jim3ma approved these changes

2021-08-02 12:14 UTC, merged