Feature/grpc metrics
dragonflyoss/Dragonfly2 pull request #686
Opened 2021-09-27 09:08 UTC by gaius-qi

## Description
- Refactor grpc server.
- Add scheduler grpc metrics.
- Add cdn grpc metrics.

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [x] Code compiles correctly.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-09-28 06:54 UTC, jim3ma requested changes

2021-09-28 06:54 UTC, jim3ma commented on cdn/cdn.go
> +	s.metricServer = metric.New(cfg.Metric, grpcServer)
The metric should be optional

2021-09-30 09:07 UTC, jim3ma approved these changes

2021-09-30 09:31 UTC, yxxhero approved these changes

2021-09-30 09:32 UTC, merged