docs(zh-CN): refactor machine translation
dragonflyoss/Dragonfly2 pull request #783
Opened 2021-11-04 10:18 UTC by zzy987

## Description

Remove machine translations.

## Related Issue
#781 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-05 08:22 UTC, jim3ma commented
Discard the change of `deploy/helm-charts`.

2021-11-25 17:55 UTC, 244372610 approved these changes

2021-11-25 23:16 UTC, yxxhero commented on docs/zh-CN/cli-reference/README.md
> +如何使用命令行来启动 dragonfly 可能是您遇到的第一个问题。 [CLI Reference](cli-reference)目录下的文档介绍了使用命令行启动 Dragonfly 的发方法，包括`dfget`、`cdn`、`scheduler`和`manager`等子系统的启动。您可以找到命令的简介、示例和可选参数。
您遇到的第一个问题可能是如何使用命令行来启动 dragonfly

2021-11-25 23:16 UTC, yxxhero commented on docs/zh-CN/cli-reference/README.md
通过和由保留一个

2021-11-25 23:16 UTC, yxxhero commented on docs/zh-CN/cli-reference/dfget.md
> +如果您想要在 Terminal 中查看日志，请使用 --console 将环境变量 console 设置为 true。
请使用 --console参数，或者将环境变量 console 设置为 true。

2021-11-25 23:16 UTC, yxxhero commented on docs/zh-CN/cli-reference/dfget.md
see above.

2021-11-26 07:10 UTC, yxxhero commented
need rebase @zzy987

2021-12-01 12:28 UTC, yxxhero commented
@zzy987 Please fix conflicts. Thanks very much.

2021-12-01 12:30 UTC, jim3ma approved these changes

2021-12-01 12:34 UTC, jim3ma requested changes
Update helm-charts

2021-12-02 12:34 UTC, yxxhero submitted a review, later dismissed

2021-12-02 12:35 UTC, yxxhero commented
@zzy987 Please fix markdown lint issue. Thanks very much.

2021-12-02 14:19 UTC, yxxhero commented
@zzy987 Thanks very  much agagin. Thank for your work.

2021-12-02 14:20 UTC, yxxhero reviewed
LGTM

2021-12-02 14:20 UTC, yxxhero approved these changes

2021-12-03 05:06 UTC, yxxhero commented
@zzy987 you should mark the request changes to be resolved. So I can merged it.

2021-12-03 05:20 UTC, merged