chore:make piece size util code clean
dragonflyoss/Dragonfly2 pull request #889
Opened 2021-12-07 11:53 UTC by qwtsc

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-07 13:18 UTC, gaius-qi requested changes

2021-12-07 13:18 UTC, gaius-qi commented on internal/util/util_test.go
> +			want: PieceSizeLowerBound,
expect

2021-12-07 13:30 UTC, yxxhero commented on internal/util/util.go
> +		return PieceSizeUpperBound
<= and >

2021-12-08 02:10 UTC, qwtsc commented
This pr contains compatibility problem, so close it temporarily.

2021-12-08 02:10 UTC, closed without merging