add CDN piece download cost
dragonflyoss/Dragonfly2 pull request #966
Opened 2021-12-30 04:31 UTC by 244372610

Signed-off-by: sunwp <244372610@qq.com>

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [ ] Code compiles correctly.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-30 06:07 UTC, gaius-qi requested changes
Refer to the `PieceResult` field.

2022-01-05 06:37 UTC, jim3ma approved these changes
LGTM

2022-01-05 13:57 UTC, gaius-qi requested changes

2022-01-05 13:57 UTC, gaius-qi commented on cdn/rpcserver/rpcserver.go
> +				DownloadCost: piece.DownloadCost,
`PieceInfo` needs to be consistent with the `PieceResult` of  `scheduler.proto`.

https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/rpc/scheduler/scheduler.proto#L96
https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/rpc/scheduler/scheduler.proto#L98

2022-01-05 13:57 UTC, gaius-qi commented on cdn/rpcserver/rpcserver.go
> +				DownloadCost: piece.DownloadCost,
`PieceInfo` needs to be consistent with the `PieceResult` of  `scheduler.proto`.

https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/rpc/scheduler/scheduler.proto#L96
https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/rpc/scheduler/scheduler.proto#L98

2022-03-02 11:51 UTC, gaius-qi requested changes

2022-03-02 11:51 UTC, gaius-qi commented on cdn/supervisor/cdn/cache_writer.go
> +				downloadCost:      uint64(end.Sub(start).Milliseconds()),
Use `time.Now().UnixNano()`, refer to https://github.com/dragonflyoss/Dragonfly2/blob/main/client/daemon/peer/piece_manager.go#L186

2022-03-02 11:51 UTC, gaius-qi commented on pkg/rpc/base/base.pb.validate.go
> +	return m.validate(false)
Check your dependency library version.

2022-03-02 11:53 UTC, gaius-qi requested changes

2022-03-02 11:53 UTC, gaius-qi commented on cdn/supervisor/cdn/cache_writer.go
> +				beginDownloadTime: uint64(start.UnixMilli()),
Use time.Now().UnixNano(), refer to https://github.com/dragonflyoss/Dragonfly2/blob/main/client/daemon/peer/piece_manager.go#L186

2022-03-02 11:53 UTC, gaius-qi commented on cdn/supervisor/cdn/cache_writer.go
> +				endDownloadTime:   uint64(end.UnixMilli()),
Use time.Now().UnixNano(), refer to https://github.com/dragonflyoss/Dragonfly2/blob/main/client/daemon/peer/piece_manager.go#L186

2022-03-03 06:05 UTC, gaius-qi approved these changes
LGTM

2022-03-03 06:30 UTC, gaius-qi approved these changes
LGTM

2022-03-03 06:50 UTC, jim3ma approved these changes
LGTM

2022-03-03 06:51 UTC, merged